name: stafup
description: 'ITI Placements - Employer'
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.2
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.3.1
  itq_utils: ^2.0.7
  connectivity_plus: ^6.0.5
  lottie: ^3.1.2
  provider: ^6.0.5
  get: ^4.6.6
  easy_localization: ^3.0.7
  flutter_bloc: ^9.0.0
  google_fonts: ^6.2.1
  logger: ^2.5.0
  credential_manager: ^2.0.2
  crypto: ^3.0.1
  flutter_feather_icons: ^2.0.0+1
  pin_code_fields: ^8.0.1
  fpdart: ^1.1.0
  bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  cached_network_image: ^3.2.3
  pull_to_refresh_flutter3: ^2.0.2
  shimmer: ^3.0.0
  persistent_bottom_nav_bar: ^6.2.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https:
  # For details regarding adding assets from package dependencies, see
  # https:
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https:
flutter_native_splash:
  # Background color for the splash screen (use hex color codes)
  color: '#FFFFFF' # Example: White background
  # Optional: Background color for dark mode
  # color_dark: "#000000" # Example: Black background for dark mode

  # The image asset to show on the splash screen
  image: assets/images/logo.png
