// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjESwnZAqWTwFP_U2KjnSfuF_T-hRc2pY',
    appId: '1:1012069754938:android:b23fa7b910b81a878bad03',
    messagingSenderId: '1012069754938',
    projectId: 'appixo',
    storageBucket: 'appixo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfTtvDqq1t5g0BrcyQWHzbcrSLnkZMVuk',
    appId: '1:1012069754938:ios:4ab377f4cd9f4e288bad03',
    messagingSenderId: '1012069754938',
    projectId: 'appixo',
    storageBucket: 'appixo.appspot.com',
    androidClientId: '1012069754938-0gf90igbsfhcfpdbhj1l7bv7lhlm03oa.apps.googleusercontent.com',
    iosClientId: '1012069754938-og7v02tbduhs8c51rm91phn06fum4rka.apps.googleusercontent.com',
    iosBundleId: 'com.kuzushiprotean.seeker',
  );
}
